Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian11"
  config.vm.provision "file", source: "index.html", destination: "/home/vagrant/index.html"
  config.vm.network "forwarded_port", guest:80, host:8080
  
end

