name: tests unitaires
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
      - name: Install Pytest
        run: pip3 install pytest
      - uses: actions/checkout@v3
      - run: pwd; lsb_release -a
      - run: python --version
      - name: Run tests
        run: pytest TP1/test.py
      - name: Nom branche
        run: echo "Nom branche ${{ github.ref }}"
      - name: Nom OS
        run: echo "OS de la VM ${{ runner.os }}"
        
                
     
